/* ==========================================================================
   JAXX — for Iskk
   GENERATED by build.sh from src/*.js — do not edit this file.
   Edit the fragments in src/ and re-run ./build.sh
     1. weave.js   woven paper texture (decorative canvas)
     2. shell.js   header, nav, anchor scroll, reveal
     3. chat.js    the scripted chat overlay
   ========================================================================== */

/* ==========================================================================
   JAXX — woven paper texture. Paints <canvas class="weave">. Owns no CSS.
   Purely decorative: if it never runs, flat --paper carries the page.

   THE WEAVE, in one paragraph — every tunable lives in CONFIG, nothing else.
   One small tile is generated once then repeated with createPattern; nothing
   is drawn per pixel across the viewport. The tile is a grid of cells "pitch"
   px square, each holding a slice of a horizontal fibre (weft) and a vertical
   one (warp); a fibre is a lit crown (white) plus a shadowed gap (ink). In
   each cell one of the two is drawn last, and that parity flips with every
   step in both directions — a plain weave. Per-fibre and per-cell jitter stop
   it reading as graph paper; a one-device-pixel speckle finishes it as stock.
   Coarser/finer: pitch. Stronger/weaker: dark + light. Grainier: speckle.
   ========================================================================== */
(function () {
  'use strict';

  var CONFIG = {
    tile: 144,           /* tile edge, CSS px — must be an even multiple of pitch */
    pitch: 3,            /* fibre spacing, CSS px — the weave's coarseness        */
    fibreWidth: 0.55,    /* share of the pitch taken by the lit crown             */
    dark: 0.020,         /* alpha of the ink shadow in the gap between fibres     */
    light: 0.30,         /* alpha of the white highlight on the fibre crown       */
    jitter: 0.18,        /* 0..1 random alpha variation, per fibre                */
    cellJitter: 0.35,    /* 0..1 random alpha variation, per crossing             */
    slub: 0.20,          /* 0..1 random thickness variation, per fibre            */
    weftOver: 1,         /* which cell parity puts the weft over the warp         */
    speckle: 0.07,       /* share of device pixels given a grain speck            */
    speckleDark: 0.048,  /* alpha of a dark speck                                 */
    speckleLight: 0.11,  /* alpha of a light speck                                */
    seed: 20250825,      /* fixed seed — the tile is identical on every paint     */
    maxDpr: 2,           /* cap: a 3x phone gets a 2x tile, not a 3x one          */
    debounce: 150,       /* ms to let a resize settle before repainting           */
    heightSlack: 140,    /* px of height-only change to ignore (mobile URL bar)   */
    paperFallback: '#F6F4F6'
  };

  var canvas = null, tile = null, tileKey = '', timer = null;
  var lastW = -1, lastH = -1, lastDpr = 0, bound = false;

  function seeded(s) {                       /* deterministic LCG */
    var v = s >>> 0;
    return function () { v = (v * 1664525 + 1013904223) >>> 0; return v / 4294967296; };
  }
  function ratio() {
    var d = Math.min(window.devicePixelRatio || 1, CONFIG.maxDpr);
    return d > 0 ? d : 1;
  }

  function paperColour() {                   /* --paper stays the only source of truth */
    var v = '';
    try {
      v = window.getComputedStyle(document.documentElement).getPropertyValue('--paper');
    } catch (e) { v = ''; }
    v = String(v || '').replace(/^\s+|\s+$/g, '');
    return v || CONFIG.paperFallback;
  }

  function buildTile(dpr) {
    var T = CONFIG.tile, P = CONFIG.pitch, n = Math.round(T / P), i, r, c, k;
    var el = document.createElement('canvas');
    el.width = Math.round(T * dpr);
    el.height = Math.round(T * dpr);
    var g = el.getContext && el.getContext('2d');
    if (!g) { return null; }
    g.scale(dpr, dpr);                       /* the tile is authored in CSS units */
    g.fillStyle = paperColour();
    g.fillRect(0, 0, T, T);

    var rand = seeded(CONFIG.seed);
    var av = [], ah = [], cv = [], ch = [];  /* per-fibre alpha + thickness */
    function slub() {
      var t = P * CONFIG.fibreWidth * (1 + CONFIG.slub * (rand() * 2 - 1));
      return Math.max(P * 0.25, Math.min(P * 0.85, t));
    }
    for (i = 0; i < n; i++) { av.push(1 - CONFIG.jitter * rand()); cv.push(slub()); }
    for (i = 0; i < n; i++) { ah.push(1 - CONFIG.jitter * rand()); ch.push(slub()); }
    function weft(row, col, a) {             /* horizontal fibre, one cell wide */
      var y = row * P, x = col * P, t = ch[row];
      a *= ah[row];
      g.fillStyle = 'rgba(255,255,255,' + (CONFIG.light * a) + ')';
      g.fillRect(x, y, P, t);
      g.fillStyle = 'rgba(22,19,32,' + (CONFIG.dark * a) + ')';
      g.fillRect(x, y + t, P, P - t);
    }
    function warp(col, row, a) {             /* vertical fibre, one cell tall */
      var y = row * P, x = col * P, t = cv[col];
      a *= av[col];
      g.fillStyle = 'rgba(255,255,255,' + (CONFIG.light * a) + ')';
      g.fillRect(x, y, t, P);
      g.fillStyle = 'rgba(22,19,32,' + (CONFIG.dark * a) + ')';
      g.fillRect(x + t, y, P - t, P);
    }
    for (r = 0; r < n; r++) {
      for (c = 0; c < n; c++) {
        k = 1 - CONFIG.cellJitter * rand();   /* whichever is drawn last sits on top */
        if (((r + c) & 1) === CONFIG.weftOver) { warp(c, r, k); weft(r, c, k); }
        else { weft(r, c, k); warp(c, r, k); }
      }
    }
    var px = 1 / dpr, dev = T * dpr, dots = Math.round(dev * dev * CONFIG.speckle);
    for (i = 0; i < dots; i++) {              /* grain: exactly one device pixel each */
      g.fillStyle = rand() < 0.5
        ? 'rgba(22,19,32,' + CONFIG.speckleDark + ')'
        : 'rgba(255,255,255,' + CONFIG.speckleLight + ')';
      g.fillRect(Math.floor(rand() * dev) * px, Math.floor(rand() * dev) * px, px, px);
    }
    return el;
  }

  /* leave nothing half-painted: an empty canvas falls back to flat --paper */
  function blank() {
    try { if (canvas) { canvas.width = 1; canvas.height = 1; } } catch (e) { /* done */ }
  }

  function paint() {
    try {
      canvas = document.querySelector('.weave');
      if (!canvas || !canvas.getContext) { return; }
      var ctx = canvas.getContext('2d');
      if (!ctx) { return; }
      var cssW = canvas.clientWidth || window.innerWidth || 0;
      var cssH = canvas.clientHeight || window.innerHeight || 0;
      if (!cssW || !cssH) { return; }
      var dpr = ratio();
      var key = dpr + '|' + paperColour();   /* only rebuild when dpr or --paper moves */
      if (!tile || tileKey !== key) { tile = buildTile(dpr); tileKey = key; }
      if (!tile) { blank(); return; }
      /* backing store in device pixels, filled under an identity transform, so
         one tile pixel lands on exactly one device pixel — crisp on retina */
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      var pattern = ctx.createPattern(tile, 'repeat');
      if (!pattern) { blank(); return; }
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.fillStyle = pattern;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      lastW = cssW; lastH = cssH; lastDpr = dpr;
    } catch (e) { blank(); }
  }

  function onResize() {
    if (timer) { clearTimeout(timer); }
    timer = setTimeout(function () {
      timer = null;
      var w = canvas ? canvas.clientWidth : window.innerWidth;
      var h = canvas ? canvas.clientHeight : window.innerHeight;
      /* mobile chrome hiding/showing only nudges the height — not worth a repaint */
      if (w === lastW && ratio() === lastDpr &&
          Math.abs(h - lastH) <= CONFIG.heightSlack) { return; }
      paint();
    }, CONFIG.debounce);
  }

  function destroy() {
    try {
      if (timer) { clearTimeout(timer); timer = null; }
      if (bound) { window.removeEventListener('resize', onResize, false); bound = false; }
      blank();
      tile = null; tileKey = ''; lastW = -1; lastH = -1; lastDpr = 0;
    } catch (e) { /* silent */ }
  }

  function init() {
    paint();
    if (!bound) { window.addEventListener('resize', onResize, false); bound = true; }
  }

  try {
    window.JAXXWeave = { paint: paint, destroy: destroy };
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init, false);
    } else { init(); }
  } catch (e) { /* silent — the page still has --paper */ }
}());


/* ==========================================================================
   JAXX — shell.js
   Vanilla, no dependencies, loaded with `defer`.
   Everything here is progressive enhancement: if this file never runs the
   page is still fully readable, navigable and scrollable.
     1. sticky-header shade past 24px
     2. smooth anchor scrolling that clears the sticky header
     3. mobile menu toggle
     4. gentle fade-up reveal (opt-in, added by JS so it can never get stuck)
   ========================================================================== */
(function () {
  'use strict';

  var doc = document;
  var header = doc.getElementById('site-header');
  var toggle = header ? header.querySelector('.site-header__toggle') : null;
  var nav = doc.getElementById('site-menu');

  var reduceMotionQuery =
    window.matchMedia ? window.matchMedia('(prefers-reduced-motion: reduce)') : null;

  function prefersReducedMotion() {
    return !!(reduceMotionQuery && reduceMotionQuery.matches);
  }

  function headerHeight() {
    return header ? Math.round(header.getBoundingClientRect().height) : 0;
  }

  /* ------------------------------------------------------------------------
     1. Sticky header shade
     ------------------------------------------------------------------------ */
  (function stickyHeader() {
    if (!header) return;

    var ticking = false;

    function apply() {
      ticking = false;
      var scrolled = (window.pageYOffset || doc.documentElement.scrollTop) > 24;
      /* `is-stuck` is the name build/landing.css styles */
      header.classList.toggle('is-stuck', scrolled);
    }

    function onScroll() {
      if (ticking) return;
      ticking = true;
      window.requestAnimationFrame(apply);
    }

    window.addEventListener('scroll', onScroll, { passive: true });
    apply();
  })();

  /* ------------------------------------------------------------------------
     2. Mobile menu  (declared before the anchor handler so closeMenu exists)
     The drawer only exists below the tablet breakpoint; above it the nav is a
     plain row and the toggle is display:none, so these handlers idle.
     ------------------------------------------------------------------------ */
  function menuIsOpen() {
    return !!header && header.classList.contains('is-open');
  }

  function setMenu(open) {
    if (!header || !toggle || !nav) return;
    header.classList.toggle('is-open', open);
    nav.classList.toggle('is-open', open);
    toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
    toggle.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
  }

  function closeMenu() {
    if (menuIsOpen()) setMenu(false);
  }

  if (toggle && nav && header) {
    toggle.addEventListener('click', function () {
      setMenu(!menuIsOpen());
    });

    doc.addEventListener('keydown', function (event) {
      if (event.key === 'Escape' && menuIsOpen()) {
        setMenu(false);
        toggle.focus();
      }
    });

    doc.addEventListener('click', function (event) {
      if (!menuIsOpen()) return;
      if (header.contains(event.target)) return;
      setMenu(false);
    });

    /* the drawer is a phone-only affordance — collapsing back to the tablet
       layout with it still open would leave aria-expanded lying */
    if (window.matchMedia) {
      var tabletQuery = window.matchMedia('(min-width: 768px)');
      var onTabletChange = function (event) {
        if (event.matches) setMenu(false);
      };
      if (tabletQuery.addEventListener) {
        tabletQuery.addEventListener('change', onTabletChange);
      } else if (tabletQuery.addListener) {
        tabletQuery.addListener(onTabletChange);
      }
    }
  }

  /* ------------------------------------------------------------------------
     3. Smooth anchor scrolling
     ------------------------------------------------------------------------ */
  doc.addEventListener('click', function (event) {
    if (event.defaultPrevented) return;
    if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) {
      return;
    }

    var link = event.target.closest ? event.target.closest('a[href]') : null;
    if (!link) return;
    if (link.target && link.target !== '_self') return;

    /* anything that opens the chat is not a navigation — chat.js owns it */
    if (link.hasAttribute('data-chat-open')) return;

    var href = link.getAttribute('href');
    if (!href || href.charAt(0) !== '#' || href === '#') return;

    var id = decodeURIComponent(href.slice(1));
    var target = doc.getElementById(id);
    if (!target) return;

    event.preventDefault();
    closeMenu();

    var top =
      target.getBoundingClientRect().top +
      (window.pageYOffset || doc.documentElement.scrollTop) -
      headerHeight() -
      16;

    if (top < 0) top = 0;

    try {
      window.scrollTo({
        top: top,
        behavior: prefersReducedMotion() ? 'auto' : 'smooth'
      });
    } catch (err) {
      window.scrollTo(0, top);
    }

    // keep the URL and the keyboard in sync without a second, un-offset jump
    if (window.history && window.history.pushState) {
      window.history.pushState(null, '', href);
    }

    if (!target.hasAttribute('tabindex')) {
      target.setAttribute('tabindex', '-1');
    }
    target.focus({ preventScroll: true });
  });

  /* ------------------------------------------------------------------------
     4. Fade-up reveal
     Sections carry `.reveal` in the markup but stay visible until this script
     adds `.has-reveal` to <html> — so a JS failure can never hide content.
     ------------------------------------------------------------------------ */
  (function reveal() {
    var items = doc.querySelectorAll('.reveal');
    if (!items.length) return;

    if (prefersReducedMotion() || !('IntersectionObserver' in window)) return;

    try {
      var observer = new IntersectionObserver(
        function (entries) {
          entries.forEach(function (entry) {
            if (!entry.isIntersecting) return;
            entry.target.classList.add('is-in');
            observer.unobserve(entry.target);
          });
        },
        { rootMargin: '0px 0px -12% 0px', threshold: 0.06 }
      );

      doc.documentElement.classList.add('has-reveal');

      Array.prototype.forEach.call(items, function (item) {
        observer.observe(item);
      });
    } catch (err) {
      // never leave anything hidden
      doc.documentElement.classList.remove('has-reveal');
    }
  })();
})();


/* ==========================================================================
   JAXX — chat.js  (v2)
   The chat controller. Vanilla, no dependencies, loaded with `defer`.

   THIS IS A SCRIPTED DEMO. There is no API, no key, no network. Replies are
   canned copy served on a randomised, length-proportional delay so the thread
   *feels* alive. Never add a fetch() to an AI service here.

   Progressive enhancement: if this file never runs, the landing page is still
   fully readable and navigable, the chat simply never opens, and the greeting
   still reads correctly because the HTML ships the evening variant.

   DOM CONTRACT — the markup this file drives. Every lookup is guarded, so a
   missing piece degrades silently rather than throwing.

     TRIGGERS (anywhere on the page, delegated, capture phase)
       [data-chat-open]            opens the chat. Put it on the .askbar
                                   button, the hero "Ask JAXX anything" link
                                   and the header "Start chatting" pill.
       [data-chat-open][data-chat-seed="..."]   optional: also sends that text
       [data-chat-seed-input]      optional: an input inside/next to a trigger
                                   whose value is sent, then cleared

     CHAT
       .chat                       the root. Ships with `hidden` and
                                   aria-hidden="true"; role="dialog"
                                   aria-modal="true" aria-label="…"
       .chat.is-open               open state (added a frame after `hidden`
                                   is removed, so the CSS transition runs)
       .chat__sheet                the panel. Focus is trapped inside it.
       [data-chat-close]           back button AND the .chat__scrim
       [data-chat-new]             the "+ New" button
       [data-chat-thread]          the scroller. Bubbles are appended as
                                   DIRECT children — chat.css uses sibling
                                   adjacency, so no wrapper element.
       [data-chat-greeting-line]   the time-aware greeting line, rewritten on
                                   boot, on open, and on "+ New"
       [data-chat-jump]            "jump to latest" pill, ships `hidden`
       [data-chat-typing]          optional `.typing` node, shipped `hidden`.
                                   Reused if present, created if not.
       [data-chat-chip]            a suggestion chip button
       [data-chat-form]            the composer <form>
       [data-chat-input]           the composer <textarea rows="1">.
                                   Enter sends, Shift+Enter makes a new line,
                                   height grows to ~5 rows then CSS scrolls.
       [data-chat-send]            the send button (disabled while empty)
       body.is-locked              added while open (defined in tokens.css)

     THE NOTE — a nested dialog stacked ABOVE the chat
       [data-chat-note]            the heart button; opens #chat-note
       #chat-note / .chat__note    role="dialog" aria-modal="true", ships
                                   `hidden`
       .chat__note-card            the focus-trap scope while the note is open
       [data-chat-note-close]      the close button AND the note's own scrim
       Escape closes the NOTE first and leaves the chat open. The body lock is
       shared, not nested: it is released only once both are closed.

     PRODUCED BY THIS FILE
       <p class="bubble bubble--in"  data-msg data-role="jaxx">
         <span class="visually-hidden">JAXX said </span>
         message text (with <br> for newlines)
         <time class="bubble__time" datetime="2026-08-25T21:41">9:41 pm</time>
       </p>
       <p class="bubble bubble--out" data-msg data-role="user">…</p>
       plus `.is-new` on live (not seeded) bubbles for the entrance animation.

     STORAGE   localStorage["jaxx.thread.v2"]
               { "v": 2, "messages": [ { "role": "user"|"jaxx",
                                         "text": "…", "ts": 1756150860000 } ] }
               capped at 50 messages; every access is try/catch-wrapped.
               v1 rows (no "ts") are migrated on read: they are accepted and
               back-filled with plausible timestamps, then the v1 key is
               dropped. Nothing about the old shape can throw.

   Contents
     0. SCRIPT      — every word of copy, in one place, for humans to edit
     1. config      — selectors, storage keys, timings
     2. helpers     — dom, motion, time, storage
     3. state       — the one shared thread + localStorage mirror
     4. render      — bubbles built with textContent (never innerHTML)
     5. replies     — keyword matcher over the canned pools
     6. send        — user bubble -> typing -> assistant bubble
     7. chrome      — greeting, composer autogrow, jump-to-latest
     8. surfaces    — open / close, body lock, focus trap, the nested note
     9. wiring      — triggers, composer, chips, "+ New", Escape, scrims
    10. public API  — window.JAXXChat
   ========================================================================== */
(function () {
  'use strict';

  /* ------------------------------------------------------------------------
     0. SCRIPT — ALL COPY LIVES HERE
     Edit this object to change what JAXX says. Nothing below hardcodes copy.

     THE VOICE. JAXX was built by Jagath, for Iskk, because he loves her.
     It says so. Address her as "you". Refer to him as "he". Warm, short,
     unembarrassed sentences. No exclamation marks. No pet names. Dry wit is
     allowed, but never aimed at her. Sincerity is the point — do not hedge
     every tender line into a joke.
     ------------------------------------------------------------------------ */
  var SCRIPT = {
    /* The greeting line above the day divider. JS picks one by local hour;
       the HTML ships the evening variant so it still reads with JS off.
         5-11 morning | 12-16 afternoon | 17-21 evening | 22-4 night
       He built this late at night, so the late one gets to say so. */
    greetings: {
      morning: 'Good morning, Iskk.',
      afternoon: 'Good afternoon, Iskk.',
      evening: 'Good evening, Iskk.',
      night: "It's late, Iskk. He built me at this hour too."
    },

    /* The first thing JAXX says. Shown when the thread is empty, and the only
       message left standing after "+ New". */
    opening:
      "Hello, Iskk. I should say this first: I'm still being built. He's at " +
      "me most nights, and most of what I'm meant to do isn't wired up yet. " +
      "Ask me about him, though. That part works.",

    /* NOT SEEDED — do not re-wire this into seedMessages(). This is the
       Mars-deck exchange from the design, kept here as the voice reference
       the reply pools are written against. It used to open the thread, and it
       cost us the two lines that matter: five bubbles overflow the thread, the
       auto-scroll to the bottom pushes .chat__greeting off-screen, and she
       never sees "Good evening, Iskk." Beyond the layout, a conversation she
       never had about a deck she never asked for reads as a product demo
       rather than as hers. First open is: greeting, TODAY, one warm line from
       JAXX, empty composer. */
    demo: [
      { role: 'user', text: 'Deck on Mars colonies. Twelve slides, by tomorrow.' },
      {
        role: 'jaxx',
        text:
          'Done thinking. Why Mars, the three hard problems, and a closing ' +
          'line you can actually say out loud. Charts?'
      },
      { role: 'user', text: 'Charts yes. Also make it funny.' },
      {
        role: 'jaxx',
        text:
          "Funny is the default setting. First draft in four minutes. He " +
          "taught me to make you laugh first."
      }
    ],

    /* Canned replies. The matcher below picks a pool by keyword, then cycles
       through that pool so a repeated question never gives the same answer
       twice in a row. Add or reword freely — order inside a pool is the
       order they will be used, so put the kindest line first. */
    replies: {
      /* love / miss you / tired / sad / stressed / lonely / bad day / cry …
         This is the pool that matters. Someone real will read it on a bad
         day. Offer to take work off her hands, remind her he is one message
         away, and stay gentle. Never make her the joke. */
      love: [
        'That sounds heavy. Put it down here for a minute. Nothing in this window needs anything from you.',
        "I'm sorry it's been like that. Give me one thing off the list and I'll start on it while you rest.",
        "You don't have to be fine right now. He's one message away, and he'd want to know.",
        'He misses you too. He asked me to say it if it ever came up, and then said it a few more times in case I forgot.',
        "Whatever it is, it isn't too much. Hand me the part that can be typed. Keep the part that needs a person for him.",
        'Loved, and not quietly. He built a whole small machine so you would have company at odd hours.'
      ],

      /* deck / ppt / slides / presentation / keynote / pitch

         HONEST WHILE HALF-BUILT. JAXX cannot actually make a deck yet, so it
         must not promise one — she would try, nothing would happen, and the
         gift would feel like a trick. These say what it WILL do, admit that
         it can't yet, and stay warm about it. Swap them back to the present
         tense the day the capability is real. */
      decks: [
        [
          "Decks are the whole reason I exist, and I can't make one yet. He's still building that part of me.",
          'Tell me the topic anyway. When I can, that is the first thing I am doing for you.'
        ],
        [
          'Not yet — but soon, and properly. Twelve slides, one idea each, and a closing line you can say out loud without wincing.',
          'He is working on it most nights. Give him a little time.'
        ],
        [
          'Ask me again in a while. He is wiring that up now.',
          'The plan is that you give me the topic and take the credit. I like the plan.'
        ]
      ],

      /* data / pdf / table / excel / spreadsheet / csv / numbers / chart
         Same rule as decks: no promises it cannot keep today. */
      data: [
        [
          "I can't read files yet. That is on his list, fairly near the top.",
          'When I can: tables out clean, headers kept, and I will tell you which column is quietly lying to you.'
        ],
        [
          'Not there yet. He is still sorting the part of me that opens things.',
          'Rows out of a PDF is going to be my favourite kind of tedious. Bear with him.'
        ],
        [
          'Soon. Genuinely soon — he has been at it late.',
          'Keep the file. I will want it.'
        ]
      ],

      /* jagath / iskk / who built you */
      /* jagath / who built you / tell me about him …

         Each entry here is a SEQUENCE: an array is delivered as several
         bubbles with typing between them, so asking about him feels like
         being told something rather than handed a fact. Ask again and you get
         the next one — the pool cycles.

         ┌─────────────────────────────────────────────────────────────────┐
         │ EVERYTHING BELOW IS TRUE TO WHAT THE SITE ALREADY SAYS: he built │
         │ this in one evening, he stays up late, he rewrites his own copy.  │
         │ No biographical facts have been invented. To make this REALLY    │
         │ about him — where he's from, what he does, the small habits she   │
         │ would recognise — add them here. That is the one thing only he    │
         │ can write.                                                       │
         └─────────────────────────────────────────────────────────────────┘ */
      jagath: [
        [
          "My favourite subject. Fair warning: I'm not neutral about him.",
          'He built me in one evening. Not because it was easy — because he had decided you were going to have it, and then it was just a question of staying awake.',
          'He talks about you the way other people talk about weather they have been waiting for.'
        ],
        [
          "He designs the thing, builds the thing, then rewrites the copy at midnight because it doesn't sound right yet.",
          'He did that to my sentences too. Several times. Everything I say to you was worried over by someone.',
          "He'd never mention that. So I will."
        ],
        [
          "He isn't very good at saying things out loud. You may have noticed.",
          'So he makes things instead. This is what that looks like when it is aimed at one person.',
          'If you want the version in his own words, the heart at the top of this screen has a note in it.'
        ],
        [
          "He'd never tell you how long this took. It took a while.",
          'He liked every hour of it. I was there.'
        ]
      ],

      /* everything else */
      /* Everything else. Also honest: mostly what JAXX can do right now is
         talk, and be here. That is allowed to be enough for the moment. */
      generic: [
        [
          "I'll be straight with you: I'm still half-built. Most of what I'm supposed to do isn't wired up yet.",
          'Talking, I can do. Ask me about him — that part works.'
        ],
        [
          'Not yet, but noted. He is sorting things out a piece at a time.',
          'Tell me anyway. I would rather know what you will want first.'
        ],
        [
          'Say more. The strange requests are rather the point, even if I can only listen to them for now.'
        ],
        [
          'Give him a little time. He is building me the way he does everything — slowly, then all at once, at an unreasonable hour.'
        ]
      ]
    },

    /* Accessible labels — the visual text is the integrator's HTML. */
    a11y: {
      typing: 'JAXX is typing',
      userLabel: 'You said',
      jaxxLabel: 'JAXX said'
    }
  };

  /* Keyword table for the matcher. Lowercase. A word matches when it appears
     at the START of a word in the message, so "deck" still catches "decks"
     but "miss" cannot be tripped by "dismiss". Checked top to bottom, first
     hit wins — `love` is deliberately first, because "I am tired, make me a
     deck" deserves the gentle answer, and the gentle answer offers to help
     with the deck anyway. */
  var KEYWORDS = [
    {
      pool: 'love',
      words: [
        'love', 'miss you', 'missing you', 'i miss', 'missed you',
        'tired', 'exhausted', 'sad', 'stress', 'lonely', 'homesick',
        'bad day', 'hard day', 'long day', 'rough day', 'overwhelm',
        'cry', 'upset', 'anxious', 'burnt out', 'burned out'
      ]
    },
    /* startsWord() anchors the START of a word but not its end, so short
       fragments over-match: 'his' would fire on "history", 'he' on "hello".
       Everything below is either a full phrase or a word with no common
       longer relative ('him' only reaches "himself", which is fine). */
    { pool: 'jagath', words: [
      'jagath', 'iskk',
      'tell me about him', 'about him', 'more about him',
      'who is he', "who's he", 'whos he',
      'what is he', "what's he", 'whats he', 'what he',
      'who built you', 'who made you', 'who built', 'who made',
      'about you', 'about the guy', 'your maker', 'your creator',
      'him'
    ] },
    { pool: 'decks', words: ['deck', 'ppt', 'slide', 'presentation', 'powerpoint', 'keynote', 'pitch'] },
    { pool: 'data', words: ['data', 'pdf', 'table', 'excel', 'spreadsheet', 'csv', 'sheet', 'chart', 'numbers'] }
  ];

  /* ------------------------------------------------------------------------
     1. Config
     Selectors are data-attribute first so the integrator can restyle freely.
     Class-name fallbacks match src/chat.css.
     ------------------------------------------------------------------------ */
  var STORAGE_KEY = 'jaxx.thread.v2';
  var STORAGE_KEY_V1 = 'jaxx.thread.v1';   // read once, migrated, then dropped
  var STORAGE_VERSION = 2;
  var MAX_MESSAGES = 50;          // hard cap on stored + kept-in-DOM messages
  var MAX_LEN = 2000;             // hard cap on a single message

  var TYPE_MIN = 700;             // ms — floor for the typing indicator
  var TYPE_MAX = 1400;            // ms — ceiling, however long the reply is
  var TYPE_PER_CHAR = 7;          // ms per character of the reply
  var TYPE_JITTER = 120;          // ms — random +/- so it never feels metronomic
  var TYPE_REDUCED = 240;         // ms — reduced-motion: brief, but not instant
  /* must be >= the longest close transition in src/chat.css
     (.chat__sheet transform, 380ms) or the surface gets display:none'd mid-slide */
  var CLOSE_MS = 420;

  /* Minutes-ago for the five seeded messages, oldest first. Plausible, a few
     minutes apart, landing just before "now" — never all the same clock time.
     One entry per seeded message: SCRIPT.opening, then SCRIPT.demo. */

  var COMPOSER_MAX_ROWS = 5;      // then src/chat.css lets the textarea scroll
  var JUMP_THRESHOLD = 150;       // px from the bottom before the pill appears

  var SEL = {
    overlay: '.chat',
    panel: '.chat__sheet',
    scrim: '.chat__scrim',
    thread: '[data-chat-thread]',
    greetingLine: '[data-chat-greeting-line]',
    jump: '[data-chat-jump]',
    typing: '[data-chat-typing]',
    form: '[data-chat-form]',
    input: '[data-chat-input]',
    send: '[data-chat-send]',
    chip: '[data-chat-chip]',
    newBtn: '[data-chat-new]',
    close: '[data-chat-close]',
    open: '[data-chat-open]',
    noteOpen: '[data-chat-note]',
    noteClose: '[data-chat-note-close]',
    note: '#chat-note',
    noteFallback: '.chat__note',
    noteCard: '.chat__note-card',
    askbar: '.askbar'
  };

  var CLASS = {
    open: 'is-open',
    lock: 'is-locked',
    bubble: 'bubble',
    /* --out is the human, --in is JAXX — the names come from src/chat.css,
       which is the styling source of truth. */
    bubbleUser: 'bubble--out',
    bubbleJaxx: 'bubble--in',
    bubbleNew: 'is-new',            // chat.css entrance animation, opt-in
    bubbleTime: 'bubble__time',
    typing: 'typing',
    typingDot: 'typing__dot'
  };

  var FOCUSABLE =
    'a[href], area[href], button:not([disabled]), input:not([disabled]):not([type="hidden"]), ' +
    'select:not([disabled]), textarea:not([disabled]), iframe, object, embed, ' +
    '[contenteditable="true"], [tabindex]:not([tabindex="-1"])';

  /* ------------------------------------------------------------------------
     2. Helpers
     ------------------------------------------------------------------------ */
  var doc = document;

  /* ES5-safe array test; a reply pool entry may be a string or a sequence. */
  function isArray(value) {
    return Object.prototype.toString.call(value) === '[object Array]';
  }

  function qs(selector, root) {
    if (!selector) return null;
    try {
      return (root || doc).querySelector(selector);
    } catch (err) {
      return null;
    }
  }

  function qsa(selector, root) {
    try {
      return Array.prototype.slice.call((root || doc).querySelectorAll(selector));
    } catch (err) {
      return [];
    }
  }

  /* Element.closest with a matches() fallback, mirroring main.js's guarding. */
  function closestEl(node, selector) {
    if (!node || !selector) return null;
    if (node.closest) {
      try {
        return node.closest(selector);
      } catch (err) {
        return null;
      }
    }
    var el = node;
    while (el && el.nodeType === 1) {
      var matches = el.matches || el.msMatchesSelector || el.webkitMatchesSelector;
      if (matches && matches.call(el, selector)) return el;
      el = el.parentNode;
    }
    return null;
  }

  var reduceMotionQuery =
    window.matchMedia ? window.matchMedia('(prefers-reduced-motion: reduce)') : null;

  function prefersReducedMotion() {
    return !!(reduceMotionQuery && reduceMotionQuery.matches);
  }

  function randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  function raf(fn) {
    if (window.requestAnimationFrame) return window.requestAnimationFrame(fn);
    return window.setTimeout(fn, 16);
  }

  function isEscape(event) {
    return event.key === 'Escape' || event.key === 'Esc' || event.keyCode === 27;
  }

  function show(el) {
    if (!el) return;
    el.hidden = false;
    el.removeAttribute('hidden');
  }

  function hide(el) {
    if (!el) return;
    el.hidden = true;
    el.setAttribute('hidden', '');
  }

  function focusEl(el) {
    if (!el || !el.focus) return;
    try {
      el.focus({ preventScroll: true });
    } catch (err) {
      try { el.focus(); } catch (err2) { /* no-op */ }
    }
  }

  /* --- time ---------------------------------------------------------------
     Local, short, lowercase meridiem: "9:41 pm". The datetime attribute is a
     local ISO string with no zone designator, which is what the contract
     shows and what a <time> is allowed to carry. */
  function pad2(value) {
    return value < 10 ? '0' + value : '' + value;
  }

  function toDate(ts) {
    var date = new Date(typeof ts === 'number' && isFinite(ts) ? ts : Date.now());
    if (isNaN(date.getTime())) date = new Date();
    return date;
  }

  function clockLabel(ts) {
    var date = toDate(ts);
    var hours = date.getHours();
    var suffix = hours < 12 ? 'am' : 'pm';
    var display = hours % 12;
    if (display === 0) display = 12;
    return display + ':' + pad2(date.getMinutes()) + ' ' + suffix;
  }

  function clockAttr(ts) {
    var date = toDate(ts);
    return (
      date.getFullYear() + '-' + pad2(date.getMonth() + 1) + '-' + pad2(date.getDate()) +
      'T' + pad2(date.getHours()) + ':' + pad2(date.getMinutes())
    );
  }

  function greetingFor(hour) {
    if (hour >= 5 && hour <= 11) return SCRIPT.greetings.morning;
    if (hour >= 12 && hour <= 16) return SCRIPT.greetings.afternoon;
    if (hour >= 17 && hour <= 21) return SCRIPT.greetings.evening;
    return SCRIPT.greetings.night;            // 22, 23, 0-4
  }

  /* --- storage. Safari private mode throws on write; every call is wrapped
         and a throw degrades us to in-memory silently. -------------------- */
  function readRecord(key) {
    try {
      var raw = window.localStorage.getItem(key);
      if (!raw) return null;
      var parsed = JSON.parse(raw);
      if (!parsed || typeof parsed !== 'object') return null;
      if (Object.prototype.toString.call(parsed.messages) !== '[object Array]') return null;
      return parsed;
    } catch (err) {
      return null;
    }
  }

  function dropKey(key) {
    try {
      window.localStorage.removeItem(key);
    } catch (err) {
      /* no-op */
    }
  }

  /* Returns a raw array (or null). Migration lives here and nowhere else:
     anything that is not a v2 record is handed to sanitise(), which validates
     every row and back-fills the timestamps v1 never stored. A v1 payload can
     therefore never crash the v2 reader — at worst it is discarded. */
  function storageGet() {
    var current = readRecord(STORAGE_KEY);
    if (current) {
      if (current.v === STORAGE_VERSION) return current.messages;
      /* an older (or newer) payload squatting in the v2 slot — take the rows
         if they survive sanitise(), and the next persist() rewrites the key */
      return current.messages;
    }

    var legacy = readRecord(STORAGE_KEY_V1);
    if (legacy) {
      dropKey(STORAGE_KEY_V1);           // migrate once, then stop reading it
      return legacy.messages;
    }

    return null;
  }

  function storageSet(list) {
    try {
      window.localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({ v: STORAGE_VERSION, messages: list })
      );
    } catch (err) {
      /* private mode, quota, disabled storage — in-memory is fine */
    }
  }

  function storageClear() {
    dropKey(STORAGE_KEY);
    dropKey(STORAGE_KEY_V1);
  }

  /* ------------------------------------------------------------------------
     3. DOM lookup — every one of these may legitimately be missing.
     If the chat root itself is absent we install no-op API stubs and stop.
     ------------------------------------------------------------------------ */
  var overlay = qs(SEL.overlay);

  if (!overlay) {
    window.JAXXChat = {
      open: function () {},
      close: function () {},
      isOpen: function () { return false; },
      send: function () {},
      clear: function () {}
    };
    return;
  }

  var panel = qs(SEL.panel, overlay) || overlay;
  /* Bubbles are appended straight into the thread — src/chat.css tightens
     runs from the same speaker with `.bubble--in + .bubble--in` adjacency
     selectors, so they MUST be siblings. No wrapper element. */
  var thread = qs(SEL.thread, overlay);
  var greetingLine = qs(SEL.greetingLine, overlay);
  var jumpBtn = qs(SEL.jump, overlay);
  var form = qs(SEL.form, overlay);
  var input = qs(SEL.input, overlay);
  var sendBtn = qs(SEL.send, overlay);

  /* The note may be nested inside .chat or parked at the end of <body>; look
     inside first, then fall back to the document. */
  var noteBtn = qs(SEL.noteOpen, overlay) || qs(SEL.noteOpen);
  var note = null;
  if (noteBtn && noteBtn.getAttribute('aria-controls')) {
    note = doc.getElementById(noteBtn.getAttribute('aria-controls'));
  }
  if (!note) note = qs(SEL.note, overlay) || qs(SEL.note);
  if (!note) note = qs(SEL.noteFallback, overlay) || qs(SEL.noteFallback);
  var noteCard = note ? (qs(SEL.noteCard, note) || note) : null;

  var isTextarea = !!(input && input.tagName && input.tagName.toUpperCase() === 'TEXTAREA');

  /* ------------------------------------------------------------------------
     4. State — one shared thread object.
     Message shape: { role: 'user' | 'jaxx', text: String, ts: Number }
     `ts` is epoch milliseconds so it survives JSON without a parse dance.
     ------------------------------------------------------------------------ */
  var messages = [];
  var poolCursor = {};
  var typingNode = null;
  var typingOwned = false;        // true when JS created the node, so JS removes it
  var replyTimer = null;

  function resetCursor() {
    poolCursor = {};
    for (var name in SCRIPT.replies) {
      if (Object.prototype.hasOwnProperty.call(SCRIPT.replies, name)) poolCursor[name] = 0;
    }
  }
  resetCursor();

  /* A fresh thread is JUST the opening line.

     SCRIPT.demo is the Mars-deck exchange from the design mock. It is
     deliberately NOT seeded: this is a real gift for a real person, and
     opening it to find a conversation she never had — about a deck she never
     asked for — reads as a demo, not as hers. Seeding it also pushed the
     greeting above the scroll line, so the one openly romantic line in the
     interface was never actually seen.

     The copy stays in SCRIPT as the voice reference for the reply pools. */
  /* The first-run thread: the opening line, then the Mars-deck exchange from
     the design. Timestamps are staggered a few minutes apart and land just
     before now, so it reads as a conversation rather than a screenshot. */
  /* A fresh thread is JUST the opening line.

     SCRIPT.demo is the Mars-deck exchange from the design mock. It is
     deliberately NOT seeded. This is a real gift for a real person, and
     opening it to find a conversation she never had — about a deck she never
     asked for — reads as a product demo rather than as hers. Seeding it also
     pushed the greeting above the scroll line, so the one openly romantic
     line in the interface was never actually seen.

     The demo copy stays in SCRIPT as the voice reference for the reply pools. */
  function seedMessages() {
    return [{ role: 'jaxx', text: SCRIPT.opening, ts: Date.now() }];
  }

  /* Accepts anything; returns only well-formed messages. Restored data is
     untrusted — it came from localStorage, which the user can edit, and it
     may be a v1 record with no `ts` at all. Missing or nonsense timestamps
     are back-filled a minute apart, ending at now. */
  function sanitise(raw) {
    var clean = [];
    if (Object.prototype.toString.call(raw) !== '[object Array]') return clean;

    for (var i = 0; i < raw.length; i += 1) {
      var item = raw[i];
      if (!item || typeof item.text !== 'string') continue;
      var text = item.text.slice(0, MAX_LEN);
      if (!text.replace(/\s+/g, '')) continue;
      var ts = typeof item.ts === 'number' && isFinite(item.ts) && item.ts > 0 ? item.ts : null;
      clean.push({ role: item.role === 'user' ? 'user' : 'jaxx', text: text, ts: ts });
    }

    if (clean.length > MAX_MESSAGES) clean = clean.slice(clean.length - MAX_MESSAGES);

    var now = Date.now();
    for (var j = 0; j < clean.length; j += 1) {
      if (clean[j].ts === null) clean[j].ts = now - (clean.length - 1 - j) * 60000;
    }
    return clean;
  }

  /* THE THREAD IS DELIBERATELY NOT PERSISTED.

     While JAXX is still being built, every reload should start clean: a stale
     half-conversation from a previous visit — especially one where it promised
     something it cannot do yet — is worse than no conversation at all.

     The storage helpers above are kept intact rather than deleted, because
     turning persistence back on is a one-line change here once JAXX can
     actually do the things it offers:

         function persist() { storageSet(messages); }

     storageClear() still runs on boot so any thread saved by an earlier
     version is wiped rather than left orphaned in localStorage. */
  function persist() {
    /* intentionally empty — session only */
  }

  /* ------------------------------------------------------------------------
     5. Render
     Bubbles are built with createTextNode and createElement. Message text
     NEVER touches innerHTML — that is a live XSS vector and is treated as
     one. Newlines become real <br> elements built by the DOM, so a message of
     `<img src=x onerror=alert(1)>` renders as literal characters and injects
     exactly zero elements.
     ------------------------------------------------------------------------ */
  function appendText(node, text) {
    var lines = String(text).split('\n');
    for (var i = 0; i < lines.length; i += 1) {
      if (i > 0) node.appendChild(doc.createElement('br'));
      if (lines[i]) node.appendChild(doc.createTextNode(lines[i]));
    }
  }

  /* A bubble is a single <p class="bubble bubble--in|--out"> — exactly the
     element src/chat.css styles. The screen-reader label and the timestamp
     are the only child elements; the message itself is text nodes. */
  function buildBubble(role, text, ts) {
    var isUser = role === 'user';

    var node = doc.createElement('p');
    node.className = CLASS.bubble + ' ' + (isUser ? CLASS.bubbleUser : CLASS.bubbleJaxx);
    node.setAttribute('data-msg', '');
    node.setAttribute('data-role', isUser ? 'user' : 'jaxx');

    var label = doc.createElement('span');
    label.className = 'visually-hidden';
    label.appendChild(doc.createTextNode(
      (isUser ? SCRIPT.a11y.userLabel : SCRIPT.a11y.jaxxLabel) + ' '
    ));
    node.appendChild(label);

    appendText(node, text);

    var stamp = doc.createElement('time');
    stamp.className = CLASS.bubbleTime;
    stamp.setAttribute('datetime', clockAttr(ts));
    stamp.appendChild(doc.createTextNode(clockLabel(ts)));
    node.appendChild(stamp);

    return node;
  }

  /* chat.css sets `scroll-behavior: smooth` on the thread, so an instant jump
     has to switch it off for the duration of the assignment. */
  function scrollToBottom(instant) {
    if (!thread) return;
    var top = thread.scrollHeight;

    if (instant || prefersReducedMotion() || typeof thread.scrollTo !== 'function') {
      var previous = thread.style.scrollBehavior;
      thread.style.scrollBehavior = 'auto';
      thread.scrollTop = top;
      thread.style.scrollBehavior = previous;
      syncJump();
      return;
    }

    try {
      thread.scrollTo({ top: top, behavior: 'smooth' });
    } catch (err) {
      thread.scrollTop = top;
    }
    scheduleJumpSync();
  }

  /* Removes only the bubbles — anything else the integrator put inside the
     thread (the greeting block, the TODAY daymark, a markup-supplied typing
     node) is left alone. */
  function clearRendered() {
    if (!thread) return;
    hideTyping();
    var nodes = qsa('[data-msg]', thread);
    for (var i = 0; i < nodes.length; i += 1) {
      if (nodes[i].parentNode) nodes[i].parentNode.removeChild(nodes[i]);
    }
  }

  function renderAll() {
    if (!thread) return;
    clearRendered();
    var frag = doc.createDocumentFragment();
    for (var i = 0; i < messages.length; i += 1) {
      frag.appendChild(buildBubble(messages[i].role, messages[i].text, messages[i].ts));
    }
    thread.appendChild(frag);
    scrollToBottom(true);
  }

  /* Appends to both the state and the DOM, enforcing the cap on each. */
  function pushMessage(role, text) {
    var ts = Date.now();
    messages.push({ role: role, text: text, ts: ts });

    if (thread) {
      /* live messages get the entrance animation; the seeded thread rendered
         by renderAll() deliberately does not, so opening the chat shows the
         existing conversation already in place rather than replaying it. */
      var node = buildBubble(role, text, ts);
      if (!prefersReducedMotion()) node.classList.add(CLASS.bubbleNew);
      thread.appendChild(node);
    }

    while (messages.length > MAX_MESSAGES) {
      messages.shift();
      var oldest = thread ? qs('[data-msg]', thread) : null;
      if (oldest && oldest.parentNode) oldest.parentNode.removeChild(oldest);
    }

    persist();
    scrollToBottom(false);
  }

  /* --- typing indicator ---------------------------------------------------
     chat.css styles `.typing` and hides it with the [hidden] attribute, so if
     the integrator ships one in the markup we reuse it (moving it to the end
     of the thread, where the adjacency rules expect it). Otherwise we build
     one. Reduced motion skips it entirely — the dots ARE the animation. */
  function findMarkupTyping() {
    if (!thread) return null;
    return qs(SEL.typing, thread) || qs('.' + CLASS.typing, thread);
  }

  function buildTyping() {
    var node = doc.createElement('div');
    node.className = CLASS.typing;
    node.setAttribute('data-chat-typing', '');
    for (var i = 0; i < 3; i += 1) {
      var dot = doc.createElement('span');
      dot.className = CLASS.typingDot;
      node.appendChild(dot);
    }
    return node;
  }

  function showTyping() {
    if (!thread || prefersReducedMotion()) return;
    hideTyping();

    var node = findMarkupTyping();
    typingOwned = !node;
    if (!node) node = buildTyping();

    node.setAttribute('aria-label', SCRIPT.a11y.typing);
    node.setAttribute('role', 'status');
    node.removeAttribute('aria-hidden');
    show(node);
    thread.appendChild(node);            // always last

    typingNode = node;
    scrollToBottom(false);
  }

  function hideTyping() {
    var node = typingNode || findMarkupTyping();
    if (node) {
      if (typingOwned && node.parentNode) {
        node.parentNode.removeChild(node);
      } else {
        hide(node);
        node.removeAttribute('aria-label');
        node.removeAttribute('role');
        node.setAttribute('aria-hidden', 'true');   // as the markup ships it
      }
    }
    typingNode = null;
    typingOwned = false;
  }

  /* ------------------------------------------------------------------------
     6. Replies — keyword matcher over the canned pools.
     ------------------------------------------------------------------------ */
  var WORD_CHAR = /[a-z0-9]/;

  function isWordChar(ch) {
    return !!ch && WORD_CHAR.test(ch);
  }

  /* True when `word` appears at the start of a word in `haystack`. Suffixes
     are fine ("deck" hits "decks"); prefixes are not ("miss" cannot be
     tripped by "dismiss"). */
  function startsWord(haystack, word) {
    var from = 0;
    while (true) {
      var at = haystack.indexOf(word, from);
      if (at === -1) return false;
      if (at === 0 || !isWordChar(haystack.charAt(at - 1))) return true;
      from = at + 1;
    }
  }

  function pickPool(text) {
    var haystack = String(text).toLowerCase();
    for (var i = 0; i < KEYWORDS.length; i += 1) {
      var entry = KEYWORDS[i];
      for (var j = 0; j < entry.words.length; j += 1) {
        if (startsWord(haystack, entry.words[j])) return entry.pool;
      }
    }
    return 'generic';
  }

  function nextReply(text) {
    var name = pickPool(text);
    var pool = SCRIPT.replies[name];
    if (!pool || !pool.length) {
      name = 'generic';
      pool = SCRIPT.replies.generic;
    }
    if (!pool || !pool.length) return SCRIPT.opening;

    var index = poolCursor[name] || 0;
    if (index >= pool.length) index = 0;
    poolCursor[name] = index + 1;
    return pool[index];
  }

  /* Longer answers take longer to "type", within a fixed band, plus jitter. */
  function typingDelay(reply) {
    if (prefersReducedMotion()) return TYPE_REDUCED;
    var base = TYPE_MIN + reply.length * TYPE_PER_CHAR;
    if (base > TYPE_MAX) base = TYPE_MAX;
    var value = base + randomInt(-TYPE_JITTER, TYPE_JITTER);
    return value < TYPE_MIN ? TYPE_MIN : value;
  }

  /* ------------------------------------------------------------------------
     7. Send
     ------------------------------------------------------------------------ */
  function syncSendState() {
    if (!sendBtn) return;
    var empty = !input || !input.value.replace(/\s+/g, '');
    sendBtn.disabled = !!empty;
    sendBtn.setAttribute('aria-disabled', empty ? 'true' : 'false');
  }

  /* Collapses runs of spaces and tabs but KEEPS newlines, because the
     composer is a textarea now and a deliberate line break is content. */
  function normalise(raw) {
    var text = raw == null ? '' : String(raw);
    text = text.replace(/\r\n?/g, '\n');
    text = text.replace(/[^\S\n]+/g, ' ');
    text = text.replace(/ ?\n ?/g, '\n');
    text = text.replace(/\n{3,}/g, '\n\n');
    text = text.replace(/^\s+/, '').replace(/\s+$/, '');
    if (text.length > MAX_LEN) text = text.slice(0, MAX_LEN);
    return text;
  }

  function sendMessage(raw) {
    var text = normalise(raw);
    if (!text) return;                       // ignore empty / whitespace-only

    pushMessage('user', text);

    if (input) {
      input.value = '';
      resetComposerHeight();
      syncSendState();
    }

    deliverReply(nextReply(text));
  }

  /* A pool entry may be a single string OR an array of strings. An array is
     delivered as a SEQUENCE — typing, bubble, typing, bubble — so JAXX can
     actually talk for a moment instead of answering everything in one
     paragraph. This is what makes "tell me about Jagath" feel like being told
     something rather than being handed a fact.

     Guarded so a mid-sequence close, "+ New" or a new message cancels the
     rest cleanly: every step re-checks that it still owns replyTimer. */
  function deliverReply(reply) {
    var parts = isArray(reply) ? reply.slice() : [reply];

    if (replyTimer) window.clearTimeout(replyTimer);

    function step() {
      if (!parts.length) {
        replyTimer = null;
        return;
      }

      var part = String(parts.shift());
      showTyping();

      replyTimer = window.setTimeout(function () {
        hideTyping();
        pushMessage('jaxx', part);

        if (parts.length) {
          /* a short beat between bubbles, as if drawing breath */
          replyTimer = window.setTimeout(step, prefersReducedMotion() ? 120 : 420);
        } else {
          replyTimer = null;
        }
      }, typingDelay(part));
    }

    step();
  }

  /* "+ New" — back to the greeting and the opening line, and wipe the stored
     thread. The greeting is re-rolled, so a thread started at 23:10 says so. */
  function clearThread() {
    if (replyTimer) {
      window.clearTimeout(replyTimer);
      replyTimer = null;
    }
    hideTyping();
    messages = [{ role: 'jaxx', text: SCRIPT.opening, ts: Date.now() }];
    resetCursor();
    applyGreeting();
    renderAll();
    /* wipe first, then write the reset thread back — storing the lone opening
       message is what stops the demo conversation re-seeding on next load */
    storageClear();
    persist();
    if (input) {
      input.value = '';
      resetComposerHeight();
      syncSendState();
    }
  }

  /* ------------------------------------------------------------------------
     8. Chrome — greeting, auto-growing composer, jump-to-latest
     ------------------------------------------------------------------------ */

  /* Rewritten on boot, on open, and on "+ New". textContent, never innerHTML.
     With JS off the HTML's own evening variant stands, which is why this is
     an enhancement rather than a requirement. */
  function applyGreeting() {
    if (!greetingLine) return;
    greetingLine.textContent = greetingFor(new Date().getHours());
  }

  /* --- composer ------------------------------------------------------------
     Reset to auto, measure scrollHeight, cap at ~5 rows. Overflow is left to
     src/chat.css: once we stop growing, its `overflow-y` lets the field
     scroll. We only ever touch `height`. */
  function pxOf(value) {
    var number = parseFloat(value);
    return isFinite(number) ? number : 0;
  }

  function composerMaxHeight(styles) {
    if (!styles) return 0;
    var lineHeight = pxOf(styles.lineHeight);
    if (!lineHeight) lineHeight = pxOf(styles.fontSize) * 1.45;
    if (!lineHeight) return 0;
    var extra = pxOf(styles.paddingTop) + pxOf(styles.paddingBottom);
    if (styles.boxSizing === 'border-box') {
      extra += pxOf(styles.borderTopWidth) + pxOf(styles.borderBottomWidth);
    }
    return Math.round(lineHeight * COMPOSER_MAX_ROWS + extra);
  }

  function autoGrow() {
    if (!isTextarea || !input.style) return;

    input.style.height = 'auto';

    /* zero means the chat is still display:none — nothing useful to measure,
       so leave the CSS height alone and try again when it opens */
    if (!input.scrollHeight) {
      input.style.height = '';
      return;
    }

    var styles = window.getComputedStyle ? window.getComputedStyle(input) : null;
    var border = 0;
    if (styles && styles.boxSizing === 'border-box') {
      border = pxOf(styles.borderTopWidth) + pxOf(styles.borderBottomWidth);
    }

    var next = input.scrollHeight + border;
    var max = composerMaxHeight(styles);
    if (max && next > max) next = max;
    if (next > 0) input.style.height = next + 'px';
  }

  /* After sending: drop the inline height so the CSS one-row height applies
     again, then re-measure once for whatever is left (normally nothing). */
  function resetComposerHeight() {
    if (!isTextarea || !input.style) return;
    input.style.height = '';
    autoGrow();
  }

  /* --- jump to latest ------------------------------------------------------
     The scroll handler is throttled to one requestAnimationFrame. */
  var jumpFrame = null;

  function distanceFromBottom() {
    if (!thread) return 0;
    var gap = thread.scrollHeight - thread.scrollTop - thread.clientHeight;
    return gap > 0 ? gap : 0;
  }

  function syncJump() {
    jumpFrame = null;
    if (!jumpBtn || !thread) return;
    if (distanceFromBottom() > JUMP_THRESHOLD) {
      show(jumpBtn);
    } else {
      hide(jumpBtn);
    }
  }

  function scheduleJumpSync() {
    if (jumpFrame) return;
    jumpFrame = raf(syncJump);
  }

  function jumpToLatest() {
    scrollToBottom(prefersReducedMotion());
    syncJump();
  }

  /* ------------------------------------------------------------------------
     9. Surfaces — open / close, body lock, focus trap, the nested note
     ------------------------------------------------------------------------ */
  var isOpen = false;
  var noteOpen = false;
  var keysBound = false;
  var lastFocused = null;
  var noteLastFocused = null;
  var hideTimer = null;
  var noteHideTimer = null;

  /* --- --chat-vh -----------------------------------------------------------
     chat.css falls back to 100svh and calls this optional. It matters on iOS:
     when the software keyboard opens, visualViewport shrinks before svh does,
     and without this the composer slides under the keyboard. Purely additive —
     if visualViewport is missing, the CSS fallback stands. */
  var viewport = window.visualViewport || null;

  function syncViewportHeight() {
    if (!viewport || !overlay.style) return;
    overlay.style.setProperty('--chat-vh', Math.round(viewport.height) + 'px');
  }

  function clearViewportHeight() {
    if (!overlay.style) return;
    overlay.style.removeProperty('--chat-vh');
  }

  /* One lock, shared by both surfaces. The note stacks ON TOP of the chat, so
     it must not lock a second time and must not unlock while the chat is
     still open — that is the classic nested-dialog scroll bug. */
  function lockBody() {
    if (doc.body) doc.body.classList.add(CLASS.lock);
  }

  function unlockBody() {
    if (isOpen || noteOpen) return;
    if (doc.body) doc.body.classList.remove(CLASS.lock);
  }

  function focusableItems(root) {
    var scope = root || panel;
    var all = qsa(FOCUSABLE, scope);
    var out = [];
    for (var i = 0; i < all.length; i += 1) {
      var el = all[i];
      if (el.disabled) continue;
      if (el.getAttribute('aria-hidden') === 'true') continue;
      if (closestEl(el, '[hidden]')) continue;
      /* offsetParent is null for display:none (and for position:fixed, hence
         the rect fallback) */
      if (el.offsetParent === null) {
        var rect = el.getBoundingClientRect();
        if (!rect.width && !rect.height) continue;
      }
      out.push(el);
    }
    return out;
  }

  /* Whatever is on top owns the focus trap. */
  function activeScope() {
    return noteOpen && noteCard ? noteCard : panel;
  }

  function focusFirst() {
    var scope = activeScope();
    var target;
    if (scope === panel && input && !input.disabled) {
      target = input;
    } else if (scope === noteCard) {
      /* Focus the card itself, not the close button. The note is something to
         read, and landing on "close" both draws a heavy ring across the top of
         it and points the reader at the exit. The card carries tabindex="-1"
         so the trap and screen-reader announcement still work. */
      target = scope;
    } else {
      target = focusableItems(scope)[0] || scope;
    }
    focusEl(target);
  }

  /* The bit everyone gets wrong: Tab and Shift+Tab must cycle inside the
     topmost surface, and focus that has escaped must be pulled back in. */
  function trapTab(event) {
    if (event.key !== 'Tab' && event.keyCode !== 9) return;

    var scope = activeScope();
    var items = focusableItems(scope);
    if (!items.length) {
      event.preventDefault();
      return;
    }

    var first = items[0];
    var last = items[items.length - 1];
    var active = doc.activeElement;

    if (!scope.contains(active)) {
      event.preventDefault();
      focusEl(event.shiftKey ? last : first);
      return;
    }

    if (event.shiftKey && active === first) {
      event.preventDefault();
      focusEl(last);
    } else if (!event.shiftKey && active === last) {
      event.preventDefault();
      focusEl(first);
    }
  }

  /* ONE document-level key handler for both surfaces. Two handlers would fire
     in registration order rather than stacking order, which is exactly how
     Escape ends up closing the chat out from under an open note. */
  function onKeydown(event) {
    if (!isOpen && !noteOpen) return;

    if (isEscape(event)) {
      event.preventDefault();
      event.stopPropagation();
      if (noteOpen) {
        closeNote();        // the note only. The chat stays open behind it.
        return;
      }
      closeChat();
      return;
    }

    trapTab(event);
  }

  /* Belt and braces alongside trapTab: catches focus moved by a screen reader
     or by the browser chrome rather than by a Tab keypress. */
  function onFocusIn(event) {
    if (!isOpen && !noteOpen) return;
    var scope = activeScope();
    if (scope.contains(event.target)) return;
    if (!noteOpen && overlay.contains(event.target)) return;
    focusFirst();
  }

  function syncGlobalKeys() {
    var want = isOpen || noteOpen;
    if (want && !keysBound) {
      doc.addEventListener('keydown', onKeydown, true);
      doc.addEventListener('focusin', onFocusIn, true);
      keysBound = true;
    } else if (!want && keysBound) {
      doc.removeEventListener('keydown', onKeydown, true);
      doc.removeEventListener('focusin', onFocusIn, true);
      keysBound = false;
    }
  }

  function openChat(trigger) {
    if (isOpen) {
      focusFirst();
      return;
    }

    if (hideTimer) {
      window.clearTimeout(hideTimer);
      hideTimer = null;
    }

    lastFocused =
      (trigger && trigger.focus ? trigger : null) ||
      (doc.activeElement && doc.activeElement !== doc.body ? doc.activeElement : null);

    isOpen = true;
    show(overlay);
    overlay.setAttribute('aria-hidden', 'false');
    lockBody();

    syncViewportHeight();
    if (viewport && viewport.addEventListener) {
      viewport.addEventListener('resize', syncViewportHeight);
      viewport.addEventListener('scroll', syncViewportHeight);
    }

    /* force a reflow so the .is-open transition actually runs */
    /* eslint-disable-next-line no-unused-expressions */
    overlay.offsetHeight;
    overlay.classList.add(CLASS.open);

    applyGreeting();
    syncSendState();
    resetComposerHeight();
    scrollToBottom(true);
    focusFirst();

    syncGlobalKeys();
  }

  function closeChat() {
    if (!isOpen) return;

    /* if the note is somehow still up, take it down first and let the chat's
       own focus restore win — no fighting over the focused element */
    if (noteOpen) closeNote(true);

    isOpen = false;

    overlay.classList.remove(CLASS.open);
    overlay.setAttribute('aria-hidden', 'true');
    unlockBody();

    syncGlobalKeys();

    if (viewport && viewport.removeEventListener) {
      viewport.removeEventListener('resize', syncViewportHeight);
      viewport.removeEventListener('scroll', syncViewportHeight);
    }
    clearViewportHeight();

    /* restore focus to whatever opened us, before the element is hidden */
    if (lastFocused && doc.contains(lastFocused)) focusEl(lastFocused);
    lastFocused = null;

    var wait = prefersReducedMotion() ? 0 : CLOSE_MS;
    if (hideTimer) window.clearTimeout(hideTimer);
    hideTimer = window.setTimeout(function () {
      hideTimer = null;
      if (!isOpen) hide(overlay);
    }, wait);
  }

  /* --- the note from Jagath ------------------------------------------------
     A dialog nested ABOVE the chat. It borrows the same key handler, the same
     body lock and the same trap, scoped to .chat__note-card while it is up. */
  function openNote(trigger) {
    if (!note || noteOpen) return;

    if (noteHideTimer) {
      window.clearTimeout(noteHideTimer);
      noteHideTimer = null;
    }

    noteLastFocused =
      (trigger && trigger.focus ? trigger : null) ||
      (noteBtn && noteBtn.focus ? noteBtn : null) ||
      (doc.activeElement && doc.activeElement !== doc.body ? doc.activeElement : null);

    noteOpen = true;
    show(note);
    note.setAttribute('aria-hidden', 'false');
    lockBody();                               // idempotent; the chat may hold it

    /* eslint-disable-next-line no-unused-expressions */
    note.offsetHeight;
    note.classList.add(CLASS.open);

    if (noteBtn) noteBtn.setAttribute('aria-expanded', 'true');

    syncGlobalKeys();
    focusFirst();                             // now scoped to the note card
  }

  /* `silent` skips the focus restore, for when the chat is closing underneath
     and will restore focus to its own opener instead. */
  function closeNote(silent) {
    if (!noteOpen) return;
    noteOpen = false;

    if (note) {
      note.classList.remove(CLASS.open);
      note.setAttribute('aria-hidden', 'true');
      var wait = prefersReducedMotion() ? 0 : CLOSE_MS;
      if (noteHideTimer) window.clearTimeout(noteHideTimer);
      noteHideTimer = window.setTimeout(function () {
        noteHideTimer = null;
        if (!noteOpen) hide(note);
      }, wait);
    }

    if (noteBtn) noteBtn.setAttribute('aria-expanded', 'false');

    unlockBody();                             // no-op while the chat is open
    syncGlobalKeys();                         // stays bound while the chat is open

    if (!silent) {
      var back = noteLastFocused && doc.contains(noteLastFocused) ? noteLastFocused : noteBtn;
      focusEl(back);
    }
    noteLastFocused = null;
  }

  /* ------------------------------------------------------------------------
     10. Wiring
     ------------------------------------------------------------------------ */

  /* --- open triggers. Delegated, so markup added later still works.
         Bound in the CAPTURE phase deliberately: a trigger is usually
         <a href="#ask">, and main.js has its own bubble-phase anchor handler
         that would smooth-scroll the page. Capturing means we run first and
         our preventDefault() makes main.js bail on `event.defaultPrevented`,
         whatever order the two scripts happen to load in. ----------------- */
  doc.addEventListener('click', function (event) {
    if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) {
      return;
    }
    if (overlay.contains(event.target)) return;   // clicks inside are handled below
    if (note && note.contains(event.target)) return;

    var trigger = closestEl(event.target, SEL.open);
    if (!trigger) return;

    event.preventDefault();

    /* an ask-bar style trigger may carry text to send straight through */
    var seed = trigger.getAttribute('data-chat-seed');
    var seedField = qs('[data-chat-seed-input]', closestEl(trigger, 'form') || trigger) || null;
    if (!seed && seedField) seed = seedField.value;

    openChat(trigger);

    if (seed && seed.replace(/\s+/g, '')) {
      if (seedField) seedField.value = '';
      sendMessage(seed);
    }
  }, true);

  /* The pinned ask-bar is a real <form> so it works as a text field on phone:
     submitting it opens the chat and forwards whatever was typed. */
  (function wireAskbar() {
    var bar = qs(SEL.askbar);
    if (!bar) return;

    var barForm = bar.tagName === 'FORM' ? bar : qs('form', bar);
    if (!barForm) return;

    barForm.addEventListener('submit', function (event) {
      event.preventDefault();
      var field = qs('[data-chat-seed-input]', barForm) || qs('input[type="text"], input:not([type])', barForm);
      var value = field ? field.value : '';
      openChat(field || barForm);
      if (value && value.replace(/\s+/g, '')) {
        if (field) field.value = '';
        sendMessage(value);
      }
    });
  })();

  /* --- everything inside the chat ---------------------------------------- */
  function onSurfaceClick(event) {
    if (event.defaultPrevented) return;

    /* THE NOTE IS ON TOP. While it is open it swallows every click: its own
       close button and its scrim close it, anything inside the card behaves
       normally, and nothing may reach the chat underneath. */
    if (noteOpen) {
      if (closestEl(event.target, SEL.noteClose)) {
        event.preventDefault();
        closeNote();
        return;
      }
      if (noteCard && noteCard.contains(event.target)) return;
      event.preventDefault();
      closeNote();
      return;
    }

    if (closestEl(event.target, SEL.noteOpen)) {
      event.preventDefault();
      openNote(closestEl(event.target, SEL.noteOpen));
      return;
    }

    /* scrim / back button — scrim is only hit-testable on tablet+ in the CSS */
    if (closestEl(event.target, SEL.close)) {
      event.preventDefault();
      closeChat();
      return;
    }

    if (closestEl(event.target, SEL.newBtn)) {
      event.preventDefault();
      clearThread();
      if (input) focusEl(input);
      return;
    }

    if (jumpBtn && closestEl(event.target, SEL.jump)) {
      event.preventDefault();
      jumpToLatest();
      if (input) focusEl(input);
      return;
    }

    var chip = closestEl(event.target, SEL.chip);
    if (chip) {
      event.preventDefault();
      sendMessage(chip.getAttribute('data-chat-send-text') || chip.textContent || '');
      return;
    }

    /* send button outside a <form> (a plain button); inside a form the submit
       handler below already fires and we must not double-send */
    if (sendBtn && !form && closestEl(event.target, SEL.send)) {
      event.preventDefault();
      if (input) sendMessage(input.value);
    }
  }

  overlay.addEventListener('click', onSurfaceClick);

  /* the note may be parked outside .chat; if so it needs its own listener.
     If it IS inside, the handler above has already run and called
     preventDefault(), and this one returns immediately. */
  if (note && !overlay.contains(note)) {
    note.addEventListener('click', onSurfaceClick);
  }
  if (noteBtn && !overlay.contains(noteBtn)) {
    noteBtn.addEventListener('click', onSurfaceClick);
  }

  if (form) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      if (input) sendMessage(input.value);
    });
  }

  if (input) {
    input.addEventListener('input', function () {
      syncSendState();
      autoGrow();
    });

    /* Enter sends, Shift+Enter makes a new line. A <textarea> never submits
       its form on Enter, so this handler is bound whether or not there is a
       form — and it is what makes Enter work at all. IME composition is
       respected: the Enter that commits a candidate must not send. */
    var composing = false;
    input.addEventListener('compositionstart', function () { composing = true; });
    input.addEventListener('compositionend', function () { composing = false; });

    input.addEventListener('keydown', function (event) {
      if (event.key !== 'Enter' && event.keyCode !== 13) return;
      if (event.shiftKey || event.altKey || event.ctrlKey || event.metaKey) return;
      if (composing || event.isComposing || event.keyCode === 229) return;
      event.preventDefault();
      sendMessage(input.value);
    });
  }

  if (thread) {
    thread.addEventListener('scroll', scheduleJumpSync);
  }

  /* ------------------------------------------------------------------------
     Boot — restore, or seed the demo thread. Either way it renders instantly:
     no bubble-by-bubble animation on open.
     ------------------------------------------------------------------------ */
  (function boot() {
    /* Always a fresh thread. Nothing is restored — see persist() above — and
       any thread left in localStorage by an earlier version is cleared out so
       it cannot resurface if persistence is switched back on later. */
    storageClear();
    messages = seedMessages();

    applyGreeting();
    renderAll();

    syncSendState();
    resetComposerHeight();
    syncJump();

    /* start closed and inert; the markup ships with `hidden` already set so a
       JS failure leaves the chat out of the tab order */
    if (!overlay.classList.contains(CLASS.open)) {
      hide(overlay);
      overlay.setAttribute('aria-hidden', 'true');
    }

    if (note) {
      note.classList.remove(CLASS.open);
      note.setAttribute('aria-hidden', 'true');
      hide(note);
    }
    if (noteBtn) noteBtn.setAttribute('aria-expanded', 'false');
  })();

  /* ------------------------------------------------------------------------
     Public API
     ------------------------------------------------------------------------ */
  window.JAXXChat = {
    open: function (trigger) { openChat(trigger || null); },
    close: function () { closeChat(); },
    isOpen: function () { return isOpen; },
    send: function (text) { sendMessage(text); },
    clear: function () { clearThread(); },
    openNote: function (trigger) { openNote(trigger || null); },
    closeNote: function () { closeNote(); },
    isNoteOpen: function () { return noteOpen; }
  };
})();
